import { useEffect, useMemo, useState } from 'react';
import { Alert, AppState, SafeAreaView, ScrollView, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { api } from '@/api';
import { useWorkspace } from '@/workspace';
import { Badge, Button, Card, Field, s } from '@/ui';
import { colors } from '@/theme';
import { FocusBridge } from '@/focusBridge';
import { useAuth } from '@/auth';

const elapsed = (start: string) => Math.max(0, Math.floor((Date.now() - new Date(start).getTime()) / 1000));
export default function Focus() { const params = useLocalSearchParams<{ taskId?: string }>(); const { profile } = useAuth(); const { data, currentTask, activeSession, refresh, saveWorkState } = useWorkspace(); const chosen = data.tasks.find(t => t.id === Number(params.taskId)) || currentTask; const [tick, setTick] = useState(0); const [activity, setActivity] = useState(''); const [next, setNext] = useState(chosen?.next_micro_step || ''); const [busy, setBusy] = useState(false); useEffect(() => { const timer = setInterval(() => setTick(x => x + 1), 1000); return () => clearInterval(timer); }, []); useEffect(() => { if (chosen) setNext(chosen.next_micro_step || ''); }, [chosen?.id]);
  const seconds = useMemo(() => activeSession ? elapsed(activeSession.start_time) : 0, [activeSession, tick]); const clock = `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
  const start = async () => { if (!chosen) return; setBusy(true); try { if (chosen.status !== 'IN_PROGRESS') await api.patchTask(chosen.id, { status: 'IN_PROGRESS' }); const sameTaskSession = activeSession?.task_id === chosen.id ? activeSession : null; const session = sameTaskSession || await api.startSession(chosen.task_name, chosen.estimated_minutes || 25, chosen.id); await saveWorkState({ task_id: chosen.id, current_step: chosen.task_name, next_action: next || chosen.next_micro_step || 'Continue', last_activity: sameTaskSession ? 'Resumed work' : 'Started work', status: 'ACTIVE', active_session_id: session.id, started_at: session.start_time }); if (profile?.focus_prefs?.study_focus && await FocusBridge.isAvailable() && await FocusBridge.hasAccess()) await FocusBridge.setEnabled(true); await refresh(); } catch (e) { Alert.alert('Could not start', e instanceof Error ? e.message : 'Try again.'); } finally { setBusy(false); } };
  const pause = async () => { if (!activeSession || !chosen) return; await api.patchSession(activeSession.id, { is_paused: true }); await saveWorkState({ status: 'PAUSED', last_activity: activity.trim() || 'Paused work', next_action: next.trim() || chosen.next_micro_step }); await FocusBridge.setEnabled(false); await refresh(); };
  const resume = async () => { if (!activeSession || !chosen) return start(); await api.patchSession(activeSession.id, { is_paused: false }); await saveWorkState({ status: 'ACTIVE', last_activity: 'Resumed work', next_action: next.trim() || chosen.next_micro_step }); if (profile?.focus_prefs?.study_focus && await FocusBridge.hasAccess()) await FocusBridge.setEnabled(true); await refresh(); };
  const stop = async (complete = false) => { if (!chosen) return; if (activeSession) await api.patchSession(activeSession.id, { end_time: new Date().toISOString(), is_paused: false }); await api.patchTask(chosen.id, { status: complete ? 'COMPLETED' : 'TODO', next_micro_step: next.trim() }); await saveWorkState({ task_id: complete ? null : chosen.id, current_step: chosen.task_name, last_activity: activity.trim() || (complete ? 'Completed work' : 'Stopped work'), next_action: complete ? 'Choose the next task' : next.trim() || 'Continue where you stopped', status: 'IDLE', active_session_id: null }); await FocusBridge.setEnabled(false); await refresh(); if (complete) router.back(); };
  return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><View style={s.between}><Button variant="light" onPress={() => router.back()}>Back</Button><Badge color={activeSession?.is_paused ? colors.amber : activeSession ? colors.green : colors.ink}>{activeSession?.is_paused ? 'Paused' : activeSession ? 'Working' : 'Ready'}</Badge></View>{chosen ? <><Card accent={colors.blue}><Text style={s.eyebrow}>Current work</Text><Text style={s.h2}>{chosen.task_name}</Text><Text style={s.muted}>Current step</Text><Text style={s.h3}>{data.workState?.current_step || chosen.task_name}</Text><Text style={s.muted}>Next action</Text><Text style={s.body}>{next || 'Set the next concrete action below.'}</Text></Card><Card><Text style={{ fontFamily: 'monospace', fontSize: 56, textAlign: 'center', fontWeight: '800', color: colors.ink }}>{clock}</Text>{!activeSession && <Button busy={busy} onPress={start}>Start work</Button>}{activeSession?.is_paused && <Button onPress={resume}>Resume work</Button>}{activeSession && !activeSession.is_paused && <Button variant="light" onPress={pause}>Pause</Button>}</Card><Card><Text style={s.h3}>Leave a precise handoff</Text><Field placeholder="Last activity — e.g. Solved Example 1" value={activity} onChangeText={setActivity} /><Field placeholder="Next — e.g. Complete Example 2" value={next} onChangeText={setNext} /><Button variant="light" onPress={() => stop(false)}>Stop and save place</Button><Button onPress={() => stop(true)}>Complete task</Button></Card>{data.workState?.browser_context && <Card><Text style={s.eyebrow}>Browser context</Text><Text style={s.h3}>{data.workState.browser_context.title}</Text><Text style={s.muted} numberOfLines={2}>{data.workState.browser_context.url}</Text></Card>}</> : <Card><Text style={s.h2}>Nothing selected</Text><Text style={s.body}>Choose a task from Today or My Work.</Text><Button onPress={() => router.replace('/(tabs)/work')}>Choose work</Button></Card>}</ScrollView></SafeAreaView>;
}
