import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { api } from '@/api';
import { useWorkspace } from '@/workspace';
import { Button, Card, Field, ScreenTitle, s } from '@/ui';
import { colors } from '@/theme';
import type { WorkflowPlan } from '@/types';

type Mode = 'task' | 'goal' | 'habit' | 'workflow';
export default function Create() { const { refresh } = useWorkspace(); const [mode, setMode] = useState<Mode>('task'); const [title, setTitle] = useState(''); const [detail, setDetail] = useState(''); const [busy, setBusy] = useState(false); const [plan, setPlan] = useState<WorkflowPlan | null>(null);
  const submit = async () => { if (!title.trim() && mode !== 'workflow') return; setBusy(true); try { if (mode === 'task') await api.createTask({ task_name: title.trim(), next_micro_step: detail.trim() }); if (mode === 'goal') await api.createGoal({ title: title.trim(), description: detail.trim() }); if (mode === 'habit') await api.createHabit(title.trim()); if (mode === 'workflow') { if (!plan) { setPlan(await api.generateWorkflow(detail.trim())); return; } await api.createWorkflow({ ...plan, sop_text: detail.trim() }); setPlan(null); } setTitle(''); setDetail(''); await refresh(); Alert.alert('Saved', `Your ${mode} is available on every device.`); } catch (e) { Alert.alert('Could not save', e instanceof Error ? e.message : 'Try again.'); } finally { setBusy(false); } };
  return <ScrollView style={s.page} contentContainerStyle={s.content}><ScreenTitle eyebrow="Turn intent into action" title="Create" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{(['task','goal','habit','workflow'] as Mode[]).map(x => <Pressable key={x} onPress={() => { setMode(x); setPlan(null); }} style={{ minWidth: 88, padding: 11, backgroundColor: mode === x ? colors.blue : colors.card, borderWidth: 1.5, borderColor: colors.ink }}><Text style={{ textAlign: 'center', color: mode === x ? colors.white : colors.ink, fontWeight: '900', textTransform: 'capitalize' }}>{x}</Text></Pressable>)}</ScrollView><Card><Text style={s.h2}>{mode === 'workflow' ? 'Describe your process' : mode === 'goal' ? 'Set a goal' : mode === 'habit' ? 'Build a habit' : 'Capture a task'}</Text>{mode !== 'workflow' && <Field placeholder={mode === 'goal' ? 'Goal title' : mode === 'habit' ? 'Habit name' : 'Task name'} value={title} onChangeText={setTitle} />}{mode !== 'habit' && <Field multiline placeholder={mode === 'workflow' ? 'Paste or describe the process. WEFT AI will turn it into reusable steps.' : mode === 'goal' ? 'What does success look like?' : 'What is the next concrete action?'} value={detail} onChangeText={setDetail} />}{plan && <View style={{ gap: 8 }}><Text style={s.h3}>{plan.name}</Text>{plan.steps.map((step, i) => <Text style={s.body} key={i}>{i + 1}. {step.task_name} · {step.estimated_minutes}m</Text>)}</View>}<Button busy={busy} disabled={mode === 'workflow' ? !detail.trim() : !title.trim()} onPress={submit}>{mode === 'workflow' ? plan ? 'Save workflow' : 'Generate with AI' : `Create ${mode}`}</Button>{plan && <Button variant="light" onPress={() => setPlan(null)}>Regenerate</Button>}</Card></ScrollView>;
}
