import { Alert, Linking, Platform, ScrollView, Text, View } from 'react-native';
import * as Notifications from 'expo-notifications';
import { api } from '@/api';
import { useAuth } from '@/auth';
import { useWorkspace } from '@/workspace';
import { Button, Card, ScreenTitle, s } from '@/ui';
import { colors } from '@/theme';
import { FocusBridge } from '@/focusBridge';

export default function Settings() { const { profile, signOut, updateFocusPrefs } = useAuth(); const { data, registerDevice } = useWorkspace(); const enableNotifications = async () => { const result = await Notifications.requestPermissionsAsync(); if (!result.granted) Alert.alert('Notifications are off', 'You can enable them later in Android settings.'); else { await registerDevice(); try { const sent = await api.testPush(); Alert.alert('Notification test sent', `${sent.sent} device${sent.sent === 1 ? '' : 's'} reached.`); } catch { Alert.alert('Notifications enabled', 'This phone is registered. A test push will work after the shared backend integration is deployed.'); } } };
  const enableFocus = async () => { if (Platform.OS !== 'android') return; const available = await FocusBridge.isAvailable(); if (!available) return Alert.alert('Development build required', 'Focus Bridge needs the WEFT Expo development build. The rest of the app works in Expo Go.'); const granted = await FocusBridge.requestAccess(); if (granted) await updateFocusPrefs({ study_focus: true }); };
  return <ScrollView style={s.page} contentContainerStyle={s.content}><ScreenTitle eyebrow="Make WEFT yours" title="Settings" /><Card><Text style={s.h3}>{profile?.name || 'WEFT account'}</Text><Text style={s.muted}>{profile?.email}</Text><Text style={s.body}>The same account is used by your phone, website, and browser extension.</Text></Card><Card accent={colors.blue}><Text style={s.h2}>Focus Bridge</Text><Text style={s.body}>When you start active work, WEFT can ask Android to silence interruptions. Android requires you to grant notification-policy access first; WEFT never changes it silently.</Text><Button onPress={enableFocus}>{profile?.focus_prefs?.study_focus ? 'Study Focus configured' : 'Configure Android DND'}</Button>{profile?.focus_prefs?.study_focus && <Button variant="light" onPress={() => updateFocusPrefs({ study_focus: false }).then(() => FocusBridge.setEnabled(false))}>Turn Study Focus off</Button>}</Card><Card><Text style={s.h2}>Notifications</Text><Text style={s.body}>Deadline, focus-start and custom reminders. Remote push requires an Expo development build and Firebase configuration.</Text><Button variant="light" onPress={enableNotifications}>Enable and test notifications</Button></Card><Card><Text style={s.h2}>Google Calendar</Text><Text style={s.body}>Pull external commitments into WEFT and push scheduled work blocks using the website’s existing calendar connection.</Text><Button variant="light" onPress={async () => { try { const status = await api.calendarStatus(); if (!status.connected) return Alert.alert('Connect on the website', 'Open WEFT Website below and connect Google Calendar once.'); await api.calendarSync(); Alert.alert('Calendar synced'); } catch (e) { Alert.alert('Calendar sync failed', e instanceof Error ? e.message : 'Try again.'); } }}>Sync calendar</Button></Card><Card><Text style={s.h2}>Devices</Text>{data.devices.length ? data.devices.map(d => <View key={d.device_id} style={[s.between, { paddingVertical: 6 }]}><View><Text style={s.h3}>{d.name}</Text><Text style={s.muted}>{d.device_type} · {d.capabilities.join(', ')}</Text></View><Text style={s.muted}>{new Date(d.last_seen).toLocaleDateString()}</Text></View>) : <Text style={s.muted}>This device will appear after the shared-state backend integration is deployed.</Text>}</Card><Button variant="light" onPress={() => Linking.openURL('https://task-weave-57923630274.asia-south1.run.app')}>Open WEFT website</Button><Button variant="danger" onPress={() => signOut()}>Sign out</Button></ScrollView>;
}
