import { useState } from 'react';
import { Pressable, RefreshControl, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { api } from '@/api';
import { useWorkspace } from '@/workspace';
import { Badge, Button, Card, Empty, ScreenTitle, s } from '@/ui';
import { colors } from '@/theme';

type Segment = 'tasks' | 'goals' | 'habits' | 'workflows';
export default function Work() { const { data, refreshing, refresh } = useWorkspace(); const [segment, setSegment] = useState<Segment>('tasks'); return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} />}><ScreenTitle eyebrow="Shared across devices" title="My Work" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{(['tasks','goals','habits','workflows'] as Segment[]).map(x => <Pressable key={x} onPress={() => setSegment(x)} style={{ minWidth: 92, padding: 11, backgroundColor: segment === x ? colors.ink : colors.card, borderWidth: 1.5, borderColor: colors.ink }}><Text style={{ textAlign: 'center', color: segment === x ? colors.white : colors.ink, fontWeight: '800', textTransform: 'capitalize' }}>{x}</Text></Pressable>)}</ScrollView>
  {segment === 'tasks' && (data.tasks.length ? data.tasks.filter(t => t.status !== 'ARCHIVED').map(task => <Card key={task.id}><View style={s.between}><Badge color={task.status === 'COMPLETED' ? colors.green : task.status === 'IN_PROGRESS' ? colors.blue : colors.muted}>{task.status.replace('_',' ')}</Badge>{task.risk && <Text style={[s.muted, task.risk.risk_level === 'high' && { color: colors.red }]}>{task.risk.risk_percent}% risk</Text>}</View><Text style={[s.h3, task.status === 'COMPLETED' && { textDecorationLine: 'line-through', color: colors.muted }]}>{task.task_name}</Text>{task.next_micro_step && <Text style={s.body}>Next: {task.next_micro_step}</Text>}<View style={s.row}>{task.status !== 'COMPLETED' && <Button style={{ flex: 1 }} onPress={() => router.push({ pathname: '/focus', params: { taskId: String(task.id) } })}>{task.status === 'IN_PROGRESS' ? 'Resume' : 'Start'}</Button>}<Button variant="light" style={{ flex: 1 }} onPress={async () => { await api.patchTask(task.id, { status: task.status === 'COMPLETED' ? 'TODO' : 'COMPLETED' }); await refresh(); }}>{task.status === 'COMPLETED' ? 'Reopen' : 'Done'}</Button></View></Card>) : <Empty>No tasks yet.</Empty>)}
  {segment === 'goals' && (data.goals.length ? data.goals.map(goal => <Card key={goal.id}><Text style={s.h3}>{goal.title}</Text><Text style={s.body}>{goal.description}</Text><Text style={s.muted}>{goal.current_value} / {goal.target_value} {goal.metric} · {goal.linked_done}/{goal.linked_total} tasks done</Text><View style={{ height: 8, backgroundColor: colors.line }}><View style={{ height: 8, width: `${Math.min(100, goal.target_value ? goal.current_value / goal.target_value * 100 : 0)}%`, backgroundColor: colors.blue }} /></View><Button variant="light" onPress={async () => { await api.incrementGoal(goal.id); await refresh(); }}>Add progress</Button></Card>) : <Empty>No goals yet.</Empty>)}
  {segment === 'habits' && (data.habits.length ? data.habits.map(habit => <Card key={habit.id}><View style={s.between}><Text style={s.h3}>{habit.name}</Text><Badge color={habit.done_today ? colors.green : colors.muted}>{habit.done_today ? 'Done' : habit.cadence}</Badge></View><Text style={s.muted}>{habit.streak} streak · {habit.total_done} total check-ins</Text><Button variant={habit.done_today ? 'light' : 'dark'} onPress={async () => { await api.checkHabit(habit.id); await refresh(); }}>{habit.done_today ? 'Undo today' : 'Check in'}</Button></Card>) : <Empty>No habits yet.</Empty>)}
  {segment === 'workflows' && (data.workflows.length ? data.workflows.map(flow => <Card key={flow.id}><View style={s.between}><Badge color={flow.active ? colors.green : colors.muted}>{flow.active ? 'Active' : 'Paused'}</Badge><Text style={s.muted}>{flow.steps.length} steps</Text></View><Text style={s.h3}>{flow.name}</Text>{flow.steps.slice(0,3).map((step, i) => <Text key={i} style={s.body}>{i + 1}. {step.task_name}</Text>)}<Button onPress={async () => { await api.runWorkflow(flow.id); await refresh(); }}>Run workflow</Button></Card>) : <Empty>No workflows yet.</Empty>)}</ScrollView>; }
