import type { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, type PressableProps, type StyleProp, type TextInputProps, type ViewStyle } from 'react-native';
import { colors, shadow } from './theme';

export function ScreenTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <View style={s.titleRow}><View style={{ flex: 1 }}>{eyebrow && <Text style={s.eyebrow}>{eyebrow}</Text>}<Text style={s.h1}>{title}</Text></View>{action}</View>; }
export function Card({ children, accent, style }: PropsWithChildren<{ accent?: string; style?: object }>) { return <View style={[s.card, accent ? { borderTopColor: accent, borderTopWidth: 5 } : null, style]}>{children}</View>; }
export function Button({ children, variant = 'dark', busy, style, ...props }: PropsWithChildren<Omit<PressableProps, 'style'> & { variant?: 'dark' | 'light' | 'danger'; busy?: boolean; style?: StyleProp<ViewStyle> }>) { const palette = variant === 'dark' ? [colors.ink, colors.white] : variant === 'danger' ? [colors.red, colors.white] : [colors.card, colors.ink]; return <Pressable disabled={busy || props.disabled} style={({ pressed }) => [s.button, { backgroundColor: palette[0] }, variant === 'light' && s.lightButton, pressed && { transform: [{ translateX: 2 }, { translateY: 2 }], shadowOpacity: 0 }, style]} {...props}>{busy ? <ActivityIndicator color={palette[1]} /> : <Text style={[s.buttonText, { color: palette[1] }]}>{children}</Text>}</Pressable>; }
export function Field(props: TextInputProps) { return <TextInput placeholderTextColor={colors.muted} {...props} style={[s.field, props.multiline && { minHeight: 100, textAlignVertical: 'top' }, props.style]} />; }
export function Badge({ children, color = colors.blue }: PropsWithChildren<{ color?: string }>) { return <View style={[s.badge, { backgroundColor: color }]}><Text style={s.badgeText}>{children}</Text></View>; }
export function Empty({ children }: PropsWithChildren) { return <Card><Text style={s.empty}>{children}</Text></Card>; }
export const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.paper }, content: { padding: 18, paddingBottom: 120, gap: 16 }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 4 }, eyebrow: { fontSize: 11, fontWeight: '800', letterSpacing: 2, color: colors.blue, textTransform: 'uppercase' }, h1: { fontFamily: 'serif', fontSize: 34, lineHeight: 40, fontWeight: '700', color: colors.ink }, h2: { fontFamily: 'serif', fontSize: 23, fontWeight: '700', color: colors.ink }, h3: { fontSize: 16, fontWeight: '800', color: colors.ink }, body: { fontSize: 15, lineHeight: 22, color: colors.ink }, muted: { fontSize: 13, lineHeight: 19, color: colors.muted }, card: { backgroundColor: colors.card, borderWidth: 1.5, borderColor: colors.ink, padding: 16, gap: 10, ...shadow }, button: { minHeight: 48, paddingHorizontal: 18, paddingVertical: 13, justifyContent: 'center', alignItems: 'center', borderWidth: 1.5, borderColor: colors.ink, ...shadow }, lightButton: { backgroundColor: colors.card }, buttonText: { fontSize: 13, fontWeight: '900', letterSpacing: 1, textTransform: 'uppercase' }, field: { backgroundColor: colors.white, borderWidth: 1.5, borderColor: colors.ink, minHeight: 48, padding: 13, color: colors.ink, fontSize: 15 }, badge: { alignSelf: 'flex-start', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 2 }, badgeText: { color: colors.white, fontWeight: '900', fontSize: 10, letterSpacing: .8, textTransform: 'uppercase' }, row: { flexDirection: 'row', alignItems: 'center', gap: 10 }, between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 }, divider: { height: 1, backgroundColor: colors.line }, empty: { color: colors.muted, textAlign: 'center', paddingVertical: 18, lineHeight: 21 }, error: { color: colors.red, fontWeight: '700' },
});
